# Domain layer constants for areas

RISK_LEVELS = ["LOW", "MEDIUM", "HIGH"]

# Risk thresholds for calculations (0.0 to 1.0)
SCORE_THRESHOLD_HIGH = 0.7
SCORE_THRESHOLD_MEDIUM = 0.3

DEFAULT_INITIAL_SCORE = 0.1
SCORE_BOOST_FLOOD_WORDS = 0.5
SCORE_BOOST_LARGE_GEOM = 0.1
VETOR_COUNT_LARGE_THRESHOLD = 50
